// Generated by https://quicktype.io

interface Empresa {
    nome_fantasia: string;
    imagem: string;
}

export interface Produto {
    id_oferta:          string;
    descricao_oferta:          string;
    valor_oferta:              string;
    imagem_oferta: string;
    empresa_id: Empresa;
}
